@UnderstandingDependecies.WebApi_HostAddress = http://localhost:5123

POST {{UnderstandingDependecies.WebApi_HostAddress}}/api/Users/Create
Accept: application/json
Content-Type: application/json
{
   "fullName": ""
}

###
